#[build]
#  publish = "public/"
#  command = "cd exampleSite && hugo --gc --themesDir ../.."
  
#[build.environment]
#  HUGO_VERSION = "0.60.1"
#  HUGO_THEME = "repo"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
